apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-image
          image: prasadacr.azurecr.io/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: mssql+pyodbc://prasad:Ahens6372%23@prasad-server.database.windows.net:1433/prasad-db?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=no
      imagePullSecrets:
      - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
